### ISSUE TITLE
[Bug] 无法打字

### ISSUE THREAD

**Issue by suruibuas** [modstart-lib/linkandroid#24]

**Comment by iHunterDev** [comment]
手机上装一个微信输入法就能打字了（原生就不支持输入汉字，是因为手机上的键盘不支持所以输入不了）
<img width="582" alt="image" src="https://github.com/user-attachments/assets/0986e128-06f3-4f7b-a8cb-6c8ff0f521e5">

**Comment by modstart** [comment]
使用微信输入法，这个需要输入法支持
