### ISSUE TITLE
[Bug] Mac 版，拖拽到Applications 时提示错误

### ISSUE THREAD

**Issue by zhangsubo** [modstart-lib/linkandroid#28]
# 操作系统
15.1.1 (24B91)

# 软件版本
OSX-Apple · v0.1.0

# 下载地址
https://linkandroid.com/zh/download 中提示的  mac os apple 芯片
分别从百度网盘和夸克网盘下载。

# 错误截图
<img width="404" alt="image" src="https://github.com/user-attachments/assets/8a6f0c97-724a-48fd-8d95-d2e9e17df6bc">

**Comment by xingbocui** [comment]
github下载的可以安装，运行会提示损坏，按照https://linkandroid.com/zh/document/20操作一下

**Comment by modstart** [comment]
从这个下载最新的版本再试一下
https://github.com/modstart-lib/linkandroid/actions

**Comment by zhangsubo** [comment]
已解决
