### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by wating41** [modstart-lib/linkandroid#31]
#### Describe the bug
![image](https://github.com/user-attachments/assets/dadea7ff-a4fe-44b1-a6e1-60c14ea622f5)
![ces](https://github.com/user-attachments/assets/3078b5a5-1447-449a-a324-bb9f465f9102)
点击投屏，投屏成功但是，手机的画面没有上来。苹果M2的电脑

**Comment by modstart** [comment]
从actions中下载最新的版本再试一下
https://github.com/modstart-lib/linkandroid/actions
