### ISSUE TITLE
[Bug] V0.2.0版本,点击投屏到电脑，并且提示投屏成功，但投屏页面不显示，找不到显示投屏的窗口。

### ISSUE THREAD

**Issue by MrHua** [modstart-lib/linkandroid#35]
更新：换位0.1.0版本，投屏功能正常，暂时回退使用了。
#### Describe the bug
V0.2.0版本,点击投屏到电脑，并且提示投屏成功，但投屏页面不显示，找不到显示投屏的窗口。
![微信截图_20241203103120](https://github.com/user-attachments/assets/1f36717d-58a7-4189-a802-a6d71130b5e3)

**Comment by zhujie0508** [comment]
小米 mix 3 也是同样的问题

**Comment by nhqqxs** [comment]
一样 0.2假投屏

**Comment by zhujie0508** [comment]
邮件收到,稍后回复

**Comment by modstart** [comment]
从 actions 中下载最新版本的再试一下
https://github.com/modstart-lib/linkandroid/actions

**Comment by MrHua** [comment]
已更新到0.3.0测试版，结果一致，还是找不到显示投屏的窗口，









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "modstart-lib/linkandroid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月15日(星期天) 上午10:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [modstart-lib/linkandroid] [Bug] V0.2.0版本,点击投屏到电脑，并且提示投屏成功，但投屏页面不显示，找不到显示投屏的窗口。 (Issue #35)





 
从 actions 中下载最新版本的再试一下
 https://github.com/modstart-lib/linkandroid/actions

**Comment by modstart** [comment]
> 已更新到0.3.0测试版，结果一致，还是找不到显示投屏的窗口，
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "modstart-lib/linkandroid" ***@***.***&gt;; 发送时间:&nbsp;2024年12月15日(星期天) 上午10:17 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [modstart-lib/linkandroid] [Bug] V0.2.0版本,点击投屏到电脑，并且提示投屏成功，但投屏页面不显示，找不到显示投屏的窗口。 (Issue #35) 从 actions 中下载最新版本的再试一下 https://github.com/modstart-lib/linkandroid/actions — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

加入交流群，联系我们远程看一下

**Comment by Rocketre** [comment]
xiaomi 14一样的问题，主界面显示连接成功，没有投屏，也没有启动scrcpy。
不过手动启动linkandroid配置的scrpy，投屏倒是出来了。
附上出参图：
![PixPin_2024-12-18_09-30-49](https://github.com/user-attachments/assets/58aa4438-1adc-4fc7-88a7-14c061b0dcbc)

**Comment by XinXinkkk** [comment]
自己手动把  X:\Program Files\LinkAndroid\resources\extra\win\ 下的scrcpy文件夹复制到短目录，比如X:\APP\scrcpy   ，然后在软件设置里修改scrcpy路径为X:\APP\scrcpy   就好了

**Comment by modstart** [comment]
更新到最新的试一下，最新版已经修复了这个bug

> 自己手动把 X:\Program Files\LinkAndroid\resources\extra\win\ 下的scrcpy文件夹复制到短目录，比如X:\APP\scrcpy ，然后在软件设置里修改scrcpy路径为X:\APP\scrcpy 就好了

**Comment by zhujie0508** [comment]
邮件收到,稍后回复
