### ISSUE TITLE
[😊] 建议增加界面刷新频率自定义功能

### ISSUE THREAD

**Issue by h1code2** [modstart-lib/linkandroid#36]
首先，感谢您开发如此好用的软件！我在日常使用中发现它非常实用，尤其是在连接多台设备时。

不过，我注意到手机界面的同步速度有些慢，不知道是否可以考虑增加一个自定义界面刷新频率的功能？这样我可以根据自己的需求调整刷新频率，以提高使用体验。

再次感谢您的努力和付出！

**Comment by modstart** [comment]
最新版本已增加

**Comment by h1code2** [comment]
感谢，神仙作者。
