### ISSUE TITLE
[Bug] 点了投屏 提示投屏成功后续没反应

### ISSUE THREAD

**Issue by MinatoHikari** [modstart-lib/linkandroid#5]
#### Describe the bug
 macos15.0

已经homebrew装了scrcpy

**Comment by MinatoHikari** [comment]
手机是安卓14的
努比亚z50spro

**Comment by modstart** [comment]
可以直接运行 /Applications/LinkAndroid.app/Contents/MacOS/LinkAndroid 看一下有什么日志？

**Comment by MinatoHikari** [comment]
还需要 `brew install android-platform-tools`
