### ISSUE TITLE
[Help] 可以添加一个修改ip和端口的地方吗

### ISSUE THREAD

**Issue by skII22** [modstart-lib/linkandroid#9]
端口是有必要的，因为每次关闭安全调试端口都会随机刷新（无线调试）。
ip地址可修改方便我移动网络位置也可以进行很少的改动。

**Comment by modstart** [comment]
可以使用数据线连接后，使用软件切换为网络设备，这样会使用固定的5555端口，不要使用手机自带的无线调试

**Comment by skII22** [comment]
👌
